services:
  perpixai-app:
    build:
      context: .
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
        VITE_S3_ENDPOINT: ${VITE_S3_ENDPOINT}
        VITE_FONT_BASE_URL: ${VITE_FONT_BASE_URL}

    mem_limit: 500m
    cpus: "0.20"
    ports:
      - "4173:80"
    restart: unless-stopped
    pull_policy: build
    networks:
      - turing

networks:
  turing:
    external: true
