x-logging: &default-logging
  driver: json-file
  options:
    max-size: "10m"
    max-file: "3"

services:
  perpixai-app:
    build:
      context: .
      args:
        VITE_OBJECT_STORAGE_PUBLIC_ENDPOINT: ${VITE_OBJECT_STORAGE_PUBLIC_ENDPOINT}
        VITE_PERPIXAI_API_URL: ${VITE_PERPIXAI_API_URL}
        VITE_PERPIXAI_APP_URL: ${VITE_PERPIXAI_APP_URL}
        VITE_FONT_BASE_URL: ${VITE_FONT_BASE_URL}
        VITE_PERPIXAI_TELEGRAM_SUPPORT: ${VITE_PERPIXAI_TELEGRAM_SUPPORT}
        VITE_SENTRY_DSN: ${VITE_SENTRY_DSN}
        VITE_PERPIX_TAX_PERCENT: ${VITE_PERPIX_TAX_PERCENT}

    mem_limit: 500m
    cpus: "0.20"
    logging: *default-logging
    ports:
      - "4173:80"
    restart: unless-stopped
    pull_policy: build
    networks:
      - perpix
    env_file:
      - /opt/perpix/.env

networks:
  perpix:
    external: true
